version: 0.2
env:
  variables:
    DOCKER_BUILDKIT: 1
phases:
  install:
    runtime-versions:
      java: corretto21
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - wget https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
      - tar xz -f graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz
      - export PATH=/graalvm-community-jdk-21.0.2/bin:$PATH
      - mvn install -Dnative -DskipTests
  build:
    commands:
      - docker build . -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/c6-event-receiver:$VERSAO
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/c6-event-receiver:$VERSAO